using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace KeyValueStore.SourceGenerators;

[Generator]
public class BinarySerializerGenerator : IIncrementalGenerator
{
    private const string AttributeName = "GenerateBinarySerializerAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Шаг 1: Фильтрация синтаксиса (быстрый отбор по наличию атрибутов)
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsSyntaxTargetForGeneration(s),
                transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
            .Where(static m => m is not null)!;

        // Шаг 2: Объединение с компиляцией для получения полной семантической информации

        IncrementalValueProvider<(Compilation Compilation, ImmutableArray<ClassDeclarationSyntax?> Classes)> compilationAndClasses =
            context.CompilationProvider.Combine(classDeclarations.Collect());

        // Шаг 3: Регистрация источника генерации кода
        context.RegisterSourceOutput(compilationAndClasses,
            static (spc, source) => Execute(source.Compilation, source.Classes, spc, CancellationToken.None));
    }

    private static bool IsSyntaxTargetForGeneration(SyntaxNode node)
    {
        // Проверяем, что это класс и у него есть хотя бы один атрибут
        return node is ClassDeclarationSyntax classDecl && classDecl.AttributeLists.Count > 0;
    }

    private static ClassDeclarationSyntax? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;

        // Перебираем все атрибуты класса
        foreach (var attributeList in classDeclaration.AttributeLists)
        {
            foreach (var attribute in attributeList.Attributes)
            {
                if (context.SemanticModel.GetSymbolInfo(attribute).Symbol is IMethodSymbol attribSymbol)
                {
                    var fullName = attribSymbol.ContainingType.ToDisplayString();
                    if (fullName == AttributeName || fullName.EndsWith("." + AttributeName, StringComparison.Ordinal))
                    {
                        return classDeclaration;
                    }
                }
            }
        }

        return null;
    }

    private static void Execute(
        Compilation compilation,
        ImmutableArray<ClassDeclarationSyntax?> classes,
        SourceProductionContext context,
        CancellationToken cancellationToken = default)
    {
        if (classes.IsDefaultOrEmpty)
        {
            return;
        }

        // Избегаем дубликатов классов
        var distinctClasses = classes.Distinct();

        foreach (var classDecl in distinctClasses)
        {
            if (classDecl is null)
            {
                continue;
            }

            var semanticModel = compilation.GetSemanticModel(classDecl.SyntaxTree);

            if (semanticModel.GetDeclaredSymbol(classDecl, cancellationToken) is not INamedTypeSymbol classSymbol)
            {
                continue;
            }

            var namespaceName = classSymbol.ContainingNamespace.IsGlobalNamespace
                ? string.Empty
                : classSymbol.ContainingNamespace.ToDisplayString();

            var className = classSymbol.Name;

            // Извлекаем все публичные свойства
            var publicProperties = classSymbol.GetMembers()
                .OfType<IPropertySymbol>()
                .Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic)
                .ToList();

            var generatedCode = GenerateSerializationCode(namespaceName, className, publicProperties);

            // Имя файла должно быть уникальным
            var hintName = $"{namespaceName}.{className}.g.cs".Replace("<global namespace>.", "");
            context.AddSource(hintName, SourceText.From(generatedCode, Encoding.UTF8));
        }
    }

    private static string GenerateSerializationCode(string namespaceName, string className, List<IPropertySymbol> properties)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.IO;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(namespaceName))
        {
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");
        }

        sb.AppendLine($"    public partial class {className}");
        sb.AppendLine("    {");

        // МЕТОД СЕРИАЛИЗАЦИИ
        sb.AppendLine("        public void SerializeToBinary(Stream stream)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (stream == null) throw new ArgumentNullException(nameof(stream));");
        sb.AppendLine();
        sb.AppendLine("            using (var writer = new BinaryWriter(stream, System.Text.Encoding.UTF8, leaveOpen: true))");
        sb.AppendLine("            {");

        foreach (var prop in properties)
        {
            var typeName = prop.Type.ToDisplayString(NullableFlowState.None);

            if (typeName == "int" || typeName == "string")
            {
                sb.AppendLine($"                writer.Write(this.{prop.Name});");
            }
            else if (typeName == "System.DateTime")
            {
                sb.AppendLine($"                writer.Write(this.{prop.Name}.ToBinary());");
            }
            else
            {
                sb.AppendLine($"                // Тип {typeName} для свойства {prop.Name} не поддерживается генератором.");
            }
        }

        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        // МЕТОД ДЕСЕРИАЛИЗАЦИИ
        sb.AppendLine($"        public static {className} DeserializeFromBinary(Stream stream)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (stream == null) throw new ArgumentNullException(nameof(stream));");
        sb.AppendLine();
        sb.AppendLine($"            var instance = new {className}();");
        sb.AppendLine("            using (var reader = new BinaryReader(stream, System.Text.Encoding.UTF8, leaveOpen: true))");
        sb.AppendLine("            {");

        foreach (var prop in properties)
        {
            var typeName = prop.Type.ToDisplayString(NullableFlowState.None);

            if (typeName == "int")
            {
                sb.AppendLine($"                instance.{prop.Name} = reader.ReadInt32();");
            }
            else if (typeName == "string")
            {
                sb.AppendLine($"                instance.{prop.Name} = reader.ReadString();");
            }
            else if (typeName == "System.DateTime")
            {
                sb.AppendLine($"                instance.{prop.Name} = DateTime.FromBinary(reader.ReadInt64());");
            }
            else
            {
                sb.AppendLine($"                // Пропуск десериализации для неподдерживаемого типа {typeName} ({prop.Name}).");
            }
        }

        sb.AppendLine("            }");
        sb.AppendLine("            return instance;");
        sb.AppendLine("        }");

        sb.AppendLine("    }");

        if (!string.IsNullOrEmpty(namespaceName))
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }
}
