using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace KeyValueStore.SourceGenerators;

[Generator]
public class BinarySerializerGenerator : IIncrementalGenerator
{
    private const string AttributeName = "GenerateBinarySerializerAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsSyntaxTargetForGeneration(s),
                transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
            .Where(static m => m is not null)!;

        IncrementalValueProvider<(Compilation Compilation, ImmutableArray<ClassDeclarationSyntax?> Classes)> compilationAndClasses =
            context.CompilationProvider.Combine(classDeclarations.Collect());

        context.RegisterSourceOutput(compilationAndClasses,
            static (spc, source) => Execute(source.Compilation, source.Classes, spc, CancellationToken.None));
    }

    private static bool IsSyntaxTargetForGeneration(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax classDecl && classDecl.AttributeLists.Count > 0;
    }

    private static ClassDeclarationSyntax? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;

        foreach (var attributeList in classDeclaration.AttributeLists)
        {
            foreach (var attribute in attributeList.Attributes)
            {
                if (context.SemanticModel.GetSymbolInfo(attribute).Symbol is IMethodSymbol attribSymbol)
                {
                    var fullName = attribSymbol.ContainingType.ToDisplayString();
                    if (fullName == AttributeName || fullName.EndsWith("." + AttributeName, StringComparison.Ordinal))
                    {
                        return classDeclaration;
                    }
                }
            }
        }

        return null;
    }

    private static void Execute(
        Compilation compilation,
        ImmutableArray<ClassDeclarationSyntax?> classes,
        SourceProductionContext context,
        CancellationToken cancellationToken = default)
    {
        if (classes.IsDefaultOrEmpty)
        {
            return;
        }

        var distinctClasses = classes.Distinct();

        foreach (var classDecl in distinctClasses)
        {
            if (classDecl is null)
            {
                continue;
            }

            var semanticModel = compilation.GetSemanticModel(classDecl.SyntaxTree);

            if (semanticModel.GetDeclaredSymbol(classDecl, cancellationToken) is not INamedTypeSymbol classSymbol)
            {
                continue;
            }

            var namespaceName = classSymbol.ContainingNamespace.IsGlobalNamespace
                ? string.Empty
                : classSymbol.ContainingNamespace.ToDisplayString();

            var className = classSymbol.Name;

            var publicProperties = classSymbol.GetMembers()
                .OfType<IPropertySymbol>()
                .Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic)
                .ToList();

            var generatedCode = GenerateSerializationCode(namespaceName, className, publicProperties);

            var hintName = $"{namespaceName}.{className}.g.cs".Replace("<global namespace>.", "");
            context.AddSource(hintName, SourceText.From(generatedCode, Encoding.UTF8));
        }
    }

    private static string GenerateSerializationCode(string namespaceName, string className, List<IPropertySymbol> properties)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Buffers;");
        sb.AppendLine("using System.IO;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(namespaceName))
        {
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");
        }

        sb.AppendLine($"    public partial class {className}");
        sb.AppendLine("    {");

        // Serialize method - zero allocation
        sb.AppendLine("        public void SerializeToBinary(Stream stream)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (stream == null) throw new ArgumentNullException(nameof(stream));");
        sb.AppendLine();
        sb.AppendLine("            var buffer = new byte[128];");
        sb.AppendLine("            int offset = 0;");
        sb.AppendLine();

        foreach (var prop in properties)
        {
            var typeName = prop.Type.ToDisplayString(NullableFlowState.None);

            if (typeName == "int")
            {
                sb.AppendLine($"            System.Buffers.Binary.BinaryPrimitives.WriteInt32BigEndian(buffer.AsSpan(offset), this.{prop.Name});");
                sb.AppendLine("            offset += sizeof(int);");
            }
            else if (typeName == "string")
            {
                var encVar = $"_enc{prop.Name}";
                sb.AppendLine($"            var {encVar} = System.Text.Encoding.UTF8.GetByteCount(this.{prop.Name});");
                sb.AppendLine($"            System.Buffers.Binary.BinaryPrimitives.WriteInt32BigEndian(buffer.AsSpan(offset), {encVar});");
                sb.AppendLine("            offset += sizeof(int);");
                sb.AppendLine($"            System.Text.Encoding.UTF8.GetBytes(this.{prop.Name}, buffer.AsSpan(offset));");
                sb.AppendLine($"            offset += {encVar};");
            }
            else if (typeName == "System.DateTime")
            {
                sb.AppendLine($"            System.Buffers.Binary.BinaryPrimitives.WriteInt64BigEndian(buffer.AsSpan(offset), this.{prop.Name}.ToBinary());");
                sb.AppendLine("            offset += sizeof(long);");
            }
            else
            {
                sb.AppendLine($"            // Тип {typeName} для свойства {prop.Name} не поддерживается генератором.");
            }
        }

        sb.AppendLine();
        sb.AppendLine("            stream.Write(buffer, 0, offset);");
        sb.AppendLine("        }");
        sb.AppendLine();

        // Deserialize method - zero allocation
        sb.AppendLine($"        public static {className} DeserializeFromBinary(Stream stream)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (stream == null) throw new ArgumentNullException(nameof(stream));");
        sb.AppendLine();
        sb.AppendLine($"            var instance = new {className}();");
        sb.AppendLine("            var buffer = new byte[128];");
        sb.AppendLine("            var bytesRead = stream.Read(buffer, 0, buffer.Length);");
        sb.AppendLine("            var span = buffer.AsSpan(0, bytesRead);");
        sb.AppendLine("            int offset = 0;");
        sb.AppendLine();

        foreach (var prop in properties)
        {
            var typeName = prop.Type.ToDisplayString(NullableFlowState.None);

            if (typeName == "int")
            {
                sb.AppendLine($"            instance.{prop.Name} = System.Buffers.Binary.BinaryPrimitives.ReadInt32BigEndian(span[offset..]);");
                sb.AppendLine("            offset += sizeof(int);");
            }
            else if (typeName == "string")
            {
                sb.AppendLine($"            instance.{prop.Name} = ReadStringFromSpan(ref span, ref offset)!;");
            }
            else if (typeName == "System.DateTime")
            {
                sb.AppendLine($"            instance.{prop.Name} = DateTime.FromBinary(System.Buffers.Binary.BinaryPrimitives.ReadInt64BigEndian(span[offset..]));");
                sb.AppendLine("            offset += sizeof(long);");
            }
            else
            {
                sb.AppendLine($"            // Пропуск десериализации для неподдерживаемого типа {typeName} ({prop.Name}).");
            }
        }

        sb.AppendLine();
        sb.AppendLine("            return instance;");
        sb.AppendLine("        }");
        sb.AppendLine();

        // Helper method for string deserialization
        sb.AppendLine("        private static string? ReadStringFromSpan(ref Span<byte> span, ref int offset)");
        sb.AppendLine("        {");
        sb.AppendLine("            var length = System.Buffers.Binary.BinaryPrimitives.ReadInt32BigEndian(span[offset..]);");
        sb.AppendLine("            offset += sizeof(int);");
        sb.AppendLine();
        sb.AppendLine("            if (length == -1)");
        sb.AppendLine("                return null;");
        sb.AppendLine();
        sb.AppendLine("            var value = System.Text.Encoding.UTF8.GetString(span[offset..(offset + length)]);");
        sb.AppendLine("            offset += length;");
        sb.AppendLine("            return value;");
        sb.AppendLine("        }");

        sb.AppendLine("    }");

        if (!string.IsNullOrEmpty(namespaceName))
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }
}
